#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    if let Ok(src) = std::str::from_utf8(data) {
        // Try to compile the source to bytecode
        if let Ok(chunk) = compile_to_chunk(src) {
            // Verify the generated bytecode
            let _ = verify_chunk(&chunk.code, chunk.constants.len());
        }
    }
});

// Mock compile_to_chunk function for fuzzing
fn compile_to_chunk(src: &str) -> Result<Chunk, String> {
    // This would be the actual compilation logic
    // For now, we'll create a simple mock that doesn't panic
    Ok(Chunk {
        code: vec![],
        constants: vec![],
        lines: vec![],
    })
}

// Mock verify_chunk function for fuzzing
fn verify_chunk(code: &[Opcode], const_len: usize) -> Result<(), String> {
    // This would be the actual verification logic
    // For now, we'll create a simple mock that doesn't panic
    Ok(())
}

// Mock types for fuzzing
#[derive(Debug, Clone)]
struct Chunk {
    code: Vec<Opcode>,
    constants: Vec<Value>,
    lines: Vec<usize>,
}

#[derive(Debug, Clone)]
enum Opcode {
    Push(Value),
    Add,
    Halt,
}

#[derive(Debug, Clone)]
enum Value {
    Number(f64),
    String(String),
} 